### PR TITLE
Add calendar & expectations to README

### PR DESCRIPTION
**Pull request by expede**
Flesh out the README a bit:

- [x] Ground Rules
- [x] Calendar

[Click here](https://github.com/Finhaven/whitepaper-club/blob/286bf386d1bb0c59876d9a1c950a989820cb0a69/README.md) to see the markdown rendered/formatted

### CODE REVIEW

**Comment by carchrae** [comment]
also, maybe calendar at top - or a link to the calendar from the top.

**Comment by carchrae** [comment]
and hey, there is already a link to the calendar there!  doh!  :)

**Comment by expede** [comment]
@carchrae good suggestions! Added a table of contents 🔖

**Comment by expede** [comment]
@carchrae 

> an indication of time available.

Elaborate? Do you mean what time of day, or something else

**Comment by carchrae** [comment]
duration of presenter time, discussion, etc

**Comment by expede** [comment]
Hmm, yeah, it's a good point. It's probably going to vary quite a lot at the beginning, I think. I'm happy to submit it as an Issue to be reviewed in a few weeks, though 😄

**Comment by expede** [comment]
BAM 💥 https://github.com/Finhaven/whitepaper-club/issues/27

**Pull request merged**
